### ISSUE TITLE
Saving file name

### ISSUE THREAD

**Issue by vishalpatelz** [simonray/Invoicer#1]
Save(); takes 2 parameters I guess File name/ path and Password but password is working and file name not working.

**Comment by vishalpatelz** [comment]
sorry mistake of .pdf extension

**Comment by perryraskin** [comment]
I know this is pretty old.. but I'm having an issue with saving the file. Below is the error I'm getting. I tried doing `.Save(fullpath)` and also just `.Save(filename)` both with and without the `.pdf` at the end. Would really appreciate the help.

```
System.IO.FileNotFoundException: 'Could not load file or assembly 'MigraDoc.DocumentObjectModel, Version=1.32.4334.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb' or one of its dependencies. The system cannot find the file specified.'
```
